Quiz/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuizApp.Models;

namespace QuizApp.Controllers
{
    public class CategoriesController : Controller
    {
        private MyContext db = new MyContext();

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.QuizCategories.ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuizCategory quizCategory = db.QuizCategories.Find(id);
            if (quizCategory == null)
            {
                return HttpNotFound();
            }
            return View(quizCategory);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Category")] QuizCategory quizCategory)
        {
            if (ModelState.IsValid)
            {
                db.QuizCategories.Add(quizCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(quizCategory);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuizCategory quizCategory = db.QuizCategories.Find(id);
            if (quizCategory == null)
            {
                return HttpNotFound();
            }
            return View(quizCategory);
        }

        // POST: Categories/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Category")] QuizCategory quizCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(quizCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(quizCategory);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuizCategory quizCategory = db.QuizCategories.Find(id);
            if (quizCategory == null)
            {
                return HttpNotFound();
            }
            return View(quizCategory);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            QuizCategory quizCategory = db.QuizCategories.Find(id);
            db.QuizCategories.Remove(quizCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Quiz/Controllers/QuizzsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuizApp.Models;

namespace QuizApp.Controllers
{
    public class QuizzsController : Controller
    {
        private MyContext db = new MyContext();

        // GET: Quizzs
        public ActionResult Index()
        {
            return View(db.Quizs.ToList());
        }

        // GET: Quizzs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quizz quizz = db.Quizs.Find(id);
            if (quizz == null)
            {
                return HttpNotFound();
            }
            return View(quizz);
        }

        // GET: Quizzs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Quizzs/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Subject,Description,Category")] Quizz quizz)
        {
            if (ModelState.IsValid)
            {
                db.Quizs.Add(quizz);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(quizz);
        }

        // GET: Quizzs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quizz quizz = db.Quizs.Find(id);
            if (quizz == null)
            {
                return HttpNotFound();
            }
            return View(quizz);
        }

        // POST: Quizzs/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Subject,Description,Category")] Quizz quizz)
        {
            if (ModelState.IsValid)
            {
                db.Entry(quizz).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(quizz);
        }

        // GET: Quizzs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quizz quizz = db.Quizs.Find(id);
            if (quizz == null)
            {
                return HttpNotFound();
            }
            return View(quizz);
        }

        // POST: Quizzs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Quizz quizz = db.Quizs.Find(id);
            db.Quizs.Remove(quizz);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Quiz/Controllers/ReponsesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuizApp.Models;

namespace QuizApp.Controllers
{
    public class ReponsesController : Controller
    {
        private MyContext db = new MyContext();

        // GET: Reponses
        public ActionResult Index()
        {
            var quizReponses = db.QuizReponses.Include(q => q.QuizQuestion);
            return View(quizReponses.ToList());
        }

        // GET: Reponses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuizReponse quizReponse = db.QuizReponses.Find(id);
            if (quizReponse == null)
            {
                return HttpNotFound();
            }
            return View(quizReponse);
        }

        // GET: Reponses/Create
        public ActionResult Create()
        {
            ViewBag.QuizQuestionId = new SelectList(db.QuizQuestions, "Id", "QstText");
            return View();
        }

        // POST: Reponses/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,RespText,IsCorrect,QuizQuestionId")] QuizReponse quizReponse)
        {
            if (ModelState.IsValid)
            {
                db.QuizReponses.Add(quizReponse);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.QuizQuestionId = new SelectList(db.QuizQuestions, "Id", "QstText", quizReponse.QuizQuestionId);
            return View(quizReponse);
        }

        // GET: Reponses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuizReponse quizReponse = db.QuizReponses.Find(id);
            if (quizReponse == null)
            {
                return HttpNotFound();
            }
            ViewBag.QuizQuestionId = new SelectList(db.QuizQuestions, "Id", "QstText", quizReponse.QuizQuestionId);
            return View(quizReponse);
        }

        // POST: Reponses/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,RespText,IsCorrect,QuizQuestionId")] QuizReponse quizReponse)
        {
            if (ModelState.IsValid)
            {
                db.Entry(quizReponse).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.QuizQuestionId = new SelectList(db.QuizQuestions, "Id", "QstText", quizReponse.QuizQuestionId);
            return View(quizReponse);
        }

        // GET: Reponses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuizReponse quizReponse = db.QuizReponses.Find(id);
            if (quizReponse == null)
            {
                return HttpNotFound();
            }
            return View(quizReponse);
        }

        // POST: Reponses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            QuizReponse quizReponse = db.QuizReponses.Find(id);
            db.QuizReponses.Remove(quizReponse);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Quiz/Views/Shared/Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @******@
    @**@


    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("QUIZ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    @if (Session["Admin"] != null)
                    {
                        <li>@Html.ActionLink("Quiz Admin", "Index", "Quizzs")</li>
                        @*<li>@Html.ActionLink("Category Admin", "Index", "Categories")</li>
                            <li>@Html.ActionLink("Question Admin", "Index", "Questions")</li>*@
                        <li>@Html.ActionLink("Reponse Admin", "Index", "Reponses")</li>
                        <li>@Html.ActionLink("User Admin", "Index", "Utilisateurs")</li>
                        <li>@Html.ActionLink("Question Admin", "Index", "QuizQuestion")</li>
                        <li>@Html.ActionLink("Category Admin", "Index", "QuizCategory")</li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Session["user"] == null)
                    {
                        <li>@Html.ActionLink("Créer un compte", "Create", "Utilisateurs")</li>

                        <li>@Html.ActionLink("Connexion", "Connexion", "Login")</li>

                    }
                    else
                    {
                        <li>@Html.ActionLink("Déconnexion", "Deconnexion", "Login")</li>

                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Quiz/Views/Shared/_Layout.cshtml
@using QuizApp.Models
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title QuizT</title>
    <link href="~/Content/css/reset.css" rel="stylesheet" />

    <link rel="stylesheet/less"
          type="text/css"
          href="@Url.Content("~/content/less/style.less")" />
    <script src="//cdn.jsdelivr.net/npm/less@3.13"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body >
    <header>
        <div class="container">
            <a href="/" class="logo">
                <img src="~/Content/images/logo-TechQuizz.png" />
            </a>
            <ul class="nav navbar-right">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle btn btn-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Menu
                    </a>
                    <div class="dropdown-menu">
                        @if (Session["user_role"] != null)
                        {
                            switch (Enum.Parse(typeof(UserRole), Session["user_role"].ToString()))
                            {
                                case UserRole.ADMIN:
                                    @Html.ActionLink("Quiz Admin", "Index", "Quizzs", new { area = "" }, new { @class = "dropdown-item" })
                                    <br />
                                    @Html.ActionLink("Gestion utilisateur", "Index", "Users", new { area = "" }, new { @class = "dropdown-item" })
                                    @*@Html.ActionLink("Gestion utilisateur", "Index", "Users"}*@

                                    <br />
                                    @Html.ActionLink("Gestion categories", "Index", "QuizCategory", new { area = "" }, new { @class = "dropdown-item" })
                                    <br />
                                    @Html.ActionLink("Gestion des Questions", "Index", "QuizQuestion", new { area = "" }, new { @class = "dropdown-item" })
                                    <br />
                                    @Html.ActionLink("Reponse Admin", "Index", "Reponses", new { area = "" }, new { @class = "dropdown-item" })
                                    <br />
                                    @Html.ActionLink("Déconnexion", "Logout", "Login", new { area = "" }, new { @class = "dropdown-item" })
                                    break;
                                case UserRole.USER:
                                    @Html.ActionLink("Déconnexion", "Logout", "Login", new { area = "" }, new { @class = "dropdown-item" })
                                    break;
                            }


                        }
                        else
                        {
                            @Html.ActionLink("Connexion", "Connexion", "Login", new { area = "" }, new { @class = "dropdown-item" })
                        }
                    </div>
                </li>
                   
             </ul>
        </div>
    </header>
    <!--<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>-->
    @*@Html.ActionLink("QUIZ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
    <!--</div>-->
      @*<div class="navbar-collapse collapse">
            
        </div>*@
    <!--</div>
    </div>-->
    <div class="body-content">
        <div class="container">
            @RenderBody()
        </div>
    </div>
    <footer>
        <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>