Quiz/Models/Utilisateur.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace QuizApp.Models
{
    public class Utilisateur
    {
        public int? Id { get; set; }

        [Required]
        [Display(Name = "Nom")]
        [StringLength(250, MinimumLength = 2, ErrorMessage = "Min 2 caractères")]
        public string Name { get; set; }


        [Required]
        [MaxLength(150)]
        [EmailAddress]
        [Index(IsUnique = true)]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Mot de passe")]
        public string Password { get; set; }


        [Required]
        [Display(Name = "Role")]
        public UserRole Role { get; set; }

    }
}

Quiz/Controllers/AdminSpaceController.cs
using QuizApp.Interceptors;
using QuizApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizApp.Controllers
{
    [LoginFilter]
    [RolesFilter(UserRole.ADMIN)]
    public class AdminSpaceController : Controller
    {
        // GET: AdminSpace
        public ActionResult Index()
        {
            return View();
        }
    }
}

Quiz/Controllers/QuizManagerController.cs
using QuizApp.Interceptors;
using QuizApp.Models;
using QuizApp.Repositories;
using QuizApp.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizApp.Controllers
{
    public class QuizManagerController : Controller
    {
        // GET: QuizManager  

        private MyContext db = new MyContext();
        private IQuizService quizService;

        private IQuizQuestionService questionService;


        public QuizManagerController()
        {
            quizService = new QuizService(new QuizRepository(db));
            questionService = new QuizQuestionService(new QuizQuestionRepository(db));
        }


        // GET: Quiz
        public ActionResult Index()
        {
            ViewData["QuizList"] = QuizList;
            return View();
        }

        public IEnumerable<SelectListItem> QuizList
        {
            get
            {
                return new SelectList(quizService.FindAll(), "Id", "Subject");
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Start(FormCollection form)
        {
            Session["score"] = 0;

            int selectedQuizId = Convert.ToInt32(form.Get("SelectedQuizId"));
            Session["quizId"] = selectedQuizId;
            Session["ordre"] = 1;

            QuizQuestion qst = questionService.FindQuestion(selectedQuizId, 1);
            return View("Progress", qst);
        }


       

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Next(FormCollection form)
        {
            int score = Convert.ToInt32(Session["score"]);
            int selectedQuizId = Convert.ToInt32(Session["quizId"]);
            int ordre = Convert.ToInt32(Session["ordre"]);
            Quizz qcm = quizService.FindById(selectedQuizId);
            QuizQuestion qstEnCours = qcm.Questions[ordre - 1];

            if (!qstEnCours.IsMultiple)
            {

                int idRepSel = Convert.ToInt32(form.Get("selectedSimpleRep"));
                if (quizService.FindReponse(selectedQuizId, qstEnCours.Id, idRepSel).IsCorrect)
                {
                    score++;
                    Session["score"] = score;
                }
                else
                {
                    score--;
                    Session["score"] = score;
                }
            }
            else 
            {
                // 
                string[] reponses = form.GetValues("selectedRep[]");
                bool[] tabRep = new bool[reponses.Length];
                for (int i = 0; i < reponses.Length; i++)
                {
                    tabRep[i] = quizService.FindReponse(selectedQuizId, qstEnCours.Id,
                                                    Convert.ToInt32(reponses[i])).IsCorrect;
                }
                bool exist = tabRep.Contains(false);
                if (exist == true)
                {
                    score--;
                    Session["score"] = score;
                }

                else 
                {
                    score++;
                    Session["score"] = score;
                }
            }



            

        //On vérifie s'il reste des questions à afficher
            if (ordre<qcm.Questions.Count)
            {
                ordre++;
                Session["ordre"] = ordre;
                QuizQuestion qst = questionService.FindQuestion(selectedQuizId, ordre);
                return View("Progress", qst);
            }
            else
            {
                //afficher le score
                return View("Result");
            }
        }


   }
}

Quiz/Controllers/UtilisateursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuizApp.Controllers;
using QuizApp.Filters;
using QuizApp.Interceptors;
using QuizApp.Models;
using QuizApp.Repositories;
using QuizApp.Services;

namespace QuizAppS.Controllers
{
    [RoutePrefix("Users")]
    [Route("{action=index}")]
    [LoginFilter]
    [RolesFilter(UserRole.ADMIN)]
    public class UtilisateursController : Controller
    {
        private IUserService userService;

        private MyContext db = new MyContext();

        public UtilisateursController()
        {
            userService = new UserService(new UserRepository(db));
        }

        //[LoginFilter]
        //[RolesFilter(UserRole.ADMIN)]
        [HttpGet]
        [Route("{page?}/{maxByPage?}/{searchField?}")]
        public ActionResult Index(int page = 1, int maxByPage = MyConstants.MAX_BY_PAGE, string searchField = "")
        {
            List<Utilisateur> userLst = userService.FindAll(page, maxByPage, searchField);
            ViewBag.page = page;
            ViewBag.maxByPage = maxByPage;
            ViewBag.searchField = searchField;
            ViewBag.NextExist = userService.NextExist(page, maxByPage, searchField);
            return View("Index", userLst);
        }

        [HttpGet]
        [Route("Search")]
        public ActionResult Search([Bind(Include = "searchField")] string searchField)
        {
            return Index(searchField: searchField);
        }


        [HttpGet]
        [Route("Create")]
        public ActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        [Route("Create")]
        [ValidateAntiForgeryToken]

        public ActionResult Create([Bind(Include = "Id,Name,Email,Password,Role")] Utilisateur user)
        {
            if (ModelState.IsValid)
            {
                userService.Save(user);
                return RedirectToAction("Index");
            }
            return View(user);
        }


        [HttpGet]
        [Route("Details/{id}")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilisateur user = userService.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        [HttpGet]
        [Route("Edit/{id}")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilisateur user = userService.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }


        [HttpPost]
        [Route("Edit/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Email,Password,Role")] Utilisateur user)
        {
            if (ModelState.IsValid)
            {

                userService.Update(user);
                return RedirectToAction("Index");
            }
            return View(user);
        }

        [HttpGet]
        [Route("Delete/{id}")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilisateur user = userService.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }


        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Route("Delete/{id}")]
        public ActionResult DeleteConfirmed(int id)
        {
            userService.Remove(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Quiz/Views/Utilisateurs/Create.cshtml
@model QuizApp.Models.Utilisateur

<div class="form-color">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Utilisateur</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.Role, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }


    <div>
        @Html.ActionLink("Retour à la liste des utilisateurs", "Index")
    </div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

Quiz/Views/Utilisateurs/Delete.cshtml
@model QuizApp.Models.Utilisateur

<div class="form-color">
    <h3>Supprimer un utilisateur</h3>
    <div>
        <h4>Utilisateur</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Password)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Password)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Role)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Role)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

Quiz/Views/Utilisateurs/Details.cshtml
@model QuizApp.Models.Utilisateur

<div class="form-color">
    <h4>Utilisateur</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Quiz/Views/Utilisateurs/Edit.cshtml
@model QuizApp.Models.Utilisateur

<div class="form-color">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Utilisateur</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.Role, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Retours à les utilisateurs", "Index")
    </div>
</div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Quiz/Views/Utilisateurs/Index.cshtml
@model IEnumerable<QuizApp.Models.Utilisateur>

@{
    ViewBag.Title = "Liste des users";
}

<div class="form-color">
    <div class="card-body">
        <div class="card-body">

            @using (Html.BeginForm("Search", "Utilisateurs", FormMethod.Get))
            {
                <div class="form-group">
                    <div class="row text-center">
                        <span class="col-md-3">Recherche par nom/email :</span>
                        @Html.Editor("searchField", new { htmlAttributes = new { @class = "form-control col-md-3" } })
                        <button type="submit" name="submit" value="search" id="submit" class="btn btn-primary"><i class="fa fa-fw fa-search"></i> Rechercher</button>
                    </div>
                </div>
            }
        </div>
        <p>
            @Html.ActionLink("Ajouter un utilisateur", "Create")
        </p>
        <table>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Name)
                </td>
                <td>
                    @Html.DisplayNameFor(model => model.Email)
                </td>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelitem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelitem => item.Email)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }
        </table>
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                @if (ViewBag.Page > 1)
                {
                    <li class="page-item">
                        <a title="Page précédente" class="page-link"
                           href="@Url.Action("Index", new { page = ViewBag.Page - 1, maxByPage=ViewBag.maxByPage, searchField=ViewBag.searchField })" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                }

                <li title="Page en cours" class="page-item active"><a class="page-link" href="#">@ViewBag.Page <span class="sr-only"></span></a></li>

                @if (ViewBag.NextExist == true)
                {
                    <li class="page-item">
                        <a title="Page suivante" class="page-link" href="@Url.Action("Index", new { page = ViewBag.Page + 1, maxByPage=ViewBag.maxByPage, searchField=ViewBag.searchField })" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                }
            </ul>
        </nav>

    </div>
</div>
<div>
<<<<<<< HEAD
    @Html.ActionLink("Dashbord", "Index", "AdminSpace")
</div>
=======
    @Html.ActionLink("Retours à la liste des Admins", "Index", "QuizManager")
</div>
>>>>>>> 8921967022a046197d837e798133eeeab3b2ed14